version: '3'

services:
  app:
    container_name: templeet
    hostname: templeet
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - '80:80'
